module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.gymNames = [
    "Iron Strong Fitness",
    "Flex Zone Gym",
    "Muscle Forge Fitness",
    "Powerhouse Gym",
    "Body Blitz Fitness",
    "Peak Performance Gym",
    "Elite Edge Fitness",
    "Core Dynamics Gym",
    "Fit Fusion Studio",
    "Ironclad Fitness",
    "Muscle Matrix Gym",
    "Velocity Fitness",
    "Titan Gym",
    "Flex Appeal Fitness",
    "Fit Focus Gym",
    "Body Sculpt Studio",
    "Iron Will Fitness",
    "Pure Power Gym",
    "Muscle Factory Gym",
    "Peak Physique Fitness",
    "Core Strength Studio",
    "Fit Form Gym",
    "Ironworks Fitness",
    "Flexibility Fitness Center",
    "Muscle Magic Gym",
    "Prime Performance Gym",
    "Core Crusher Fitness",
    "Fit Nation Gym",
    "Body Balance Studio",
    "Iron Elite Fitness",
    "Strength Spot Gym",
    "Muscle Motion Gym",
    "Optimal Performance Gym",
    "Core Craze Fitness",
    "Fit & Firm Gym",
    "Body Blast Studio",
    "Iron Grip Fitness",
    "Dynamic Fitness Center",
    "Muscle Mayhem Gym",
    "Progression Performance Gym",
    "Core Connection Fitness",
    "Fit Flow Gym",
    "Body Break Studio",
    "Iron Pulse Fitness",
    "Strive Fitness Center",
    "Muscle Mania Gym",
    "Peak Progress Gym",
    "Core Fusion Fitness",
    "Fit Flex Gym",
    "Body Burn Studio",
    "Iron Oasis Fitness",
    "Dynamo Fitness Center",
    "Muscle Mastery Gym",
    "Peak Pursuit Gym",
    "Core Champions Fitness",
    "Fit Foundry Gym",
    "Body Boost Studio",
    "Iron Temple Fitness",
    "Drive Fitness Center",
    "Muscle Mission Gym",
    "Prime Peak Gym",
    "Core Crusade Fitness",
    "Fit Focus Gym",
    "Body Basics Studio",
    "Iron Core Fitness",
    "Elevation Fitness Center",
    "Muscle Madness Gym",
    "Peak Power Gym",
    "Core Catalyst Fitness",
    "Fit Factory Gym",
    "Body Breakthrough Studio",
    "Iron Beast Fitness",
    "Motion Fitness Center",
    "Muscle Max Gym",
    "Peak Performance Plus Gym",
    "Core Central Fitness",
    "Fit Force Gym",
    "Body Bar Studio",
    "Iron Intent Fitness",
    "Momentum Fitness Center",
    "Muscle Merge Gym",
    "Peak Pursuits Gym",
    "Core Crew Fitness",
    "Fit Formation Gym",
    "Body Blueprint Studio",
    "Iron Infinity Fitness",
    "Drive Fitness Center",
    "Muscle Movement Gym",
    "Peak Progressions Gym",
    "Core Creators Fitness",
    "Fit Flame Gym",
    "Body Box Studio",
    "Iron Impact Fitness",
    "Dynamo Fitness Center",
    "Muscle Metrix Gym",
    "Peak Prime Gym",
    "Core Craft Fitness",
    "Fitfinity Gym",
    "Body Burnout Studio",
    "Iron Ignite Fitness",
    "Element Fitness Center",
    "Muscle Matrix Gym",
    "Peak Pursuits Gym",
    "Core Clique Fitness",
    "Fit Flex Gym",
    "Body Basics Studio",
    "Iron Oasis Fitness",
    "Drive Fitness Center",
    "Muscle Mission Gym",
    "Peak Power Gym",
    "Core Champions Fitness",
    "Fit Foundry Gym",
    "Body Boost Studio",
    "Iron Temple Fitness",
    "Dynamo Fitness Center",
    "Muscle Mastery Gym",
    "Peak Pursuit Gym",
    "Core Crusade Fitness",
    "Fit Focus Gym",
    "Body Break Studio",
    "Iron Core Fitness",
    "Elevation Fitness Center",
    "Muscle Madness Gym",
    "Peak Power Gym",
    "Core Catalyst Fitness",
    "Fit Factory Gym",
    "Body Breakthrough Studio",
    "Iron Beast Fitness",
    "Motion Fitness Center",
    "Muscle Max Gym",
    "Peak Performance Plus Gym",
    "Core Central Fitness",
    "Fit Force Gym",
    "Body Bar Studio",
    "Iron Intent Fitness",
    "Momentum Fitness Center",
    "Muscle Merge Gym",
    "Peak Pursuits Gym",
    "Core Crew Fitness",
    "Fit Formation Gym",
    "Body Blueprint Studio",
    "Iron Infinity Fitness",
    "Drive Fitness Center",
    "Muscle Movement Gym",
    "Peak Progressions Gym",
    "Core Creators Fitness",
    "Fit Flame Gym",
    "Body Box Studio",
    "Iron Impact Fitness",
    "Dynamo Fitness Center",
    "Muscle Metrix Gym",
    "Peak Prime Gym",
    "Core Craft Fitness",
    "Fitfinity Gym",
    "Body Burnout Studio",
    "Iron Ignite Fitness",
    "Element Fitness Center",
    "Muscle Matrix Gym",
    "Peak Pursuits Gym",
    "Core Clique Fitness",
    "Fit Flex Gym",
    "Body Basics Studio",
    "Iron Oasis Fitness",
    "Drive Fitness Center",
    "Muscle Mission Gym",
    "Peak Power Gym",
    "Core Champions Fitness",
    "Fit Foundry Gym",
    "Body Boost Studio",
    "Iron Temple Fitness",
    "Dynamo Fitness Center",
    "Muscle Mastery Gym",
    "Peak Pursuit Gym",
    "Core Crusade Fitness",
    "Fit Focus Gym",
    "Body Break Studio",
    "Iron Core Fitness",
    "Elevation Fitness Center",
    "Muscle Madness Gym",
    "Peak Power Gym",
    "Core Catalyst Fitness",
    "Fit Factory Gym",
    "Body Breakthrough Studio",
    "Iron Beast Fitness",
    "Motion Fitness Center",
    "Muscle Max Gym",
    "Peak Performance Plus Gym",
    "Core Central Fitness",
    "Fit Force Gym",
    "Body Bar Studio",
    "Iron Intent Fitness",
    "Momentum Fitness Center",
    "Muscle Merge Gym",
    "Peak Pursuits Gym",
    "Core Crew Fitness",
    "Fit Formation Gym",
    "Body Blueprint Studio",
    "Iron Infinity Fitness",
    "Drive Fitness Center",
    "Muscle Movement Gym",
    "Peak Progressions Gym",
    "Core Creators Fitness",
    "Fit Flame Gym",
    "Body Box Studio",
    "Iron Impact Fitness",
    "Dynamo Fitness Center",
    "Muscle Metrix Gym",
    "Peak Prime Gym",
    "Core Craft Fitness",
    "Fitfinity Gym",
    "Body Burnout Studio",
    "Iron Ignite Fitness",
    "Element Fitness Center"
];

module.exports.gymDescriptions = [
    "A gym dedicated to building ironclad strength and endurance. Our state-of-the-art equipment and expert trainers will help you achieve your fitness goals.",
    "Welcome to Flex Zone Gym, where flexibility meets strength. Our dynamic workouts and personalized training programs will help you achieve a leaner, more flexible physique.",
    "At Muscle Forge Fitness, we believe in sculpting your body into a work of art. Our intense workouts and comprehensive training plans will help you forge the physique of your dreams.",
    "Powerhouse Gym is your ultimate destination for strength training and muscle building. With top-of-the-line equipment and experienced trainers, we'll help you unlock your full potential.",
    "Get ready to blitz your fitness goals at Body Blitz Fitness. Our high-energy classes and cutting-edge equipment will help you transform your body and elevate your performance.",
    "Reach new heights of fitness at Peak Performance Gym. Whether you're an athlete or a fitness enthusiast, our tailored programs will optimize your performance and maximize your results.",
    "Discover the elite edge of fitness at Elite Edge Fitness. Our innovative workouts and personalized coaching will push you to surpass your limits and achieve unparalleled results.",
    "Strengthen your core and transform your body at Core Dynamics Gym. Our focus on core stability and functional training will help you build a strong foundation for overall fitness.",
    "Experience the fusion of fitness and fun at Fit Fusion Studio. With a diverse range of classes and expert instructors, we'll help you find joy in your fitness journey.",
    "Build an ironclad physique with our comprehensive approach to strength training and conditioning. Let us help you sculpt a body that's as strong as steel.",
    "Enter the muscle matrix and unlock your full potential. With cutting-edge equipment and personalized training, we'll help you build muscle and achieve your fitness goals.",
    "Elevate your fitness journey at our premier gym. With state-of-the-art equipment and experienced trainers, we'll help you reach your goals and surpass your expectations.",
    "Experience the ultimate workout experience at our fitness center. Our diverse range of classes and personalized training plans ensure that there's something for everyone.",
    "Unlock your full potential with our dynamic workouts and innovative training techniques. Let us help you become the best version of yourself.",
    "Train like a champion at our gym. Whether you're a seasoned athlete or just starting out, our expert trainers will guide you every step of the way.",
    "Transform your body and mind at our fitness studio. Our holistic approach to wellness focuses on strength, flexibility, and mental clarity.",
    "Discover the power of fitness at our state-of-the-art facility. With a supportive community and motivating atmosphere, you'll be inspired to push yourself to new heights.",
    "Join us on a journey to better health and fitness. With our personalized approach to training, you'll see results faster than you ever thought possible.",
    "Achieve your fitness goals with our proven methods and dedicated trainers. No matter your age or fitness level, we'll help you succeed.",
    "Experience the thrill of transformation at our gym. From weight loss to muscle gain, our expert trainers will help you achieve the results you desire.",
    "Step into our gym and step up your fitness game. With a wide range of equipment and motivating classes, you'll never get bored of working out.",
    "Embark on a fitness journey like no other. Our gym offers personalized training and state-of-the-art equipment to help you achieve your goals.",
    "Join us in the pursuit of strength, stamina, and overall wellness. With our dedicated trainers and supportive community, success is inevitable.",
    "Experience the transformational power of fitness at our gym. From cardio to strength training, we have everything you need to reach your full potential.",
    "Get ready to sweat, smile, and surpass your fitness goals. Our diverse classes and experienced instructors make working out fun and effective.",
    "Challenge yourself to be better than yesterday. With our expert guidance and motivating atmosphere, you'll exceed even your own expectations.",
    "At our gym, we believe that fitness is not just a goal, but a way of life. Let us help you live your healthiest, happiest life.",
    "Discover the joy of movement and the thrill of progress. With our supportive staff and welcoming environment, you'll love coming to the gym.",
    "Transform your body, mind, and spirit at our fitness center. With our holistic approach to wellness, you'll achieve balance in all aspects of your life.",
    "Join our community of fitness enthusiasts and experience the power of group motivation. Together, we'll crush our goals and celebrate our victories.",
    "Take your fitness to the next level with our cutting-edge equipment and innovative training programs. Your journey to a stronger, healthier you starts here.",
    "Welcome to our fitness haven where your goals become achievements. With our dedicated trainers and top-notch equipment, your fitness journey is in good hands.",
    "At our gym, we're more than just a place to work out — we're a community committed to helping you thrive. Join us and discover your potential.",
    "Achieve the body and mindset you've always dreamed of with our comprehensive approach to fitness. Let us be your partner on the path to success.",
    "Experience the rush of endorphins and the satisfaction of progress at our gym. Whether you're a beginner or a seasoned athlete, we have something for everyone.",
    "Ignite your passion for fitness and unleash your inner athlete with our challenging workouts and supportive environment. Your best self starts here.",
    "Join us in our pursuit of excellence as we push boundaries and break barriers together. With dedication and determination, anything is possible.",
    "Transform your body and your life at our gym. With personalized training and unwavering support, you'll achieve results you never thought possible.",
    "Step into our gym and step up to the challenge. With our world-class facilities and expert trainers, you'll reach new heights of strength and stamina.",
    "Discover the joy of movement and the thrill of progress at our fitness center. Let us help you become the healthiest, happiest version of yourself.",
    "Embark on a journey of self-discovery and transformation at our gym. With hard work and dedication, you'll uncover strengths you never knew you had.",
    "Welcome to our fitness sanctuary, where dedication meets determination. Join us and let's sculpt your body into a masterpiece together.",
    "At our gym, we're more than just a place to work out – we're a family dedicated to your success. Let us inspire and motivate you on your fitness journey.",
    "Transform your body, mind, and spirit with our holistic approach to fitness. From high-intensity workouts to calming yoga sessions, we have something for everyone.",
    "Join us in our mission to redefine fitness and empower lives. With our supportive community and expert guidance, you'll crush your goals and exceed your expectations.",
    "Experience the thrill of progress and the satisfaction of achievement at our gym. Let us help you unleash your full potential and become the best version of yourself.",
    "Step into our world of fitness and unlock a new level of strength, confidence, and vitality. Your journey to a healthier, happier you starts here.",
    "Discover the joy of movement and the power of perseverance at our fitness center. With dedication and determination, you'll conquer any challenge that comes your way.",
    "Ignite your passion for fitness and push your limits with our dynamic workouts and personalized training programs. Your goals are within reach – let's crush them together.",
    "Embark on a transformative journey with us and experience the incredible impact of fitness on your life. With our guidance, you'll achieve more than you ever thought possible.",
    "Join our community of like-minded individuals and let's make fitness fun again. With laughter, support, and sweat, we'll help you achieve your goals and live your best life.",
    "Welcome to our fitness oasis, where your journey to greatness begins. Join us and let's sculpt the best version of you, inside and out.",
    "At our gym, we're more than just a place to break a sweat – we're a supportive community dedicated to your success. Together, we'll crush your goals and celebrate your victories.",
    "Transform your body, mind, and spirit with our diverse range of workouts and personalized training plans. Whether you're a beginner or a seasoned athlete, we have everything you need to thrive.",
    "Join us on the path to greatness and discover the limitless potential within you. With our guidance and encouragement, you'll reach heights you never thought possible.",
    "Experience the exhilaration of progress and the satisfaction of pushing past your limits at our gym. Let us help you unleash your inner champion and achieve your fitness dreams.",
    "Step into our world of fitness and prepare to be amazed. With top-of-the-line equipment and expert trainers, you'll be inspired to elevate your workouts and exceed your goals.",
    "Discover the transformative power of fitness at our gym. From high-energy classes to one-on-one coaching, we'll help you build strength, confidence, and resilience.",
    "Ignite your passion for fitness and ignite your inner fire with our challenging workouts and supportive community. Together, we'll sweat, smile, and succeed.",
    "Embark on a journey of self-discovery and transformation with us. With dedication and determination, you'll break through barriers and emerge stronger than ever before.",
    "Join our tribe of fitness warriors and let's conquer obstacles together. With determination and support, there's no limit to what we can achieve.",
];
